---
- name: Configure Game Print Hub prod
  hosts: game_print_hub_prod
  become: true

  vars:
    # Local path to repo root (relative to playbook.yml)
    project_root_local: "{{ playbook_dir }}/../.."
    # Remote path to project root
    project_root_remote: /opt/gameprinthub

  roles:
    - docker
    - app
